# Generated by Django 2.2.16 on 2022-09-22 16:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20220921_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 22, 16, 20, 30, 343084, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
