# Generated by Django 2.2.6 on 2022-09-22 20:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 9, 22, 20, 41, 48, 986425, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
