# Generated by Django 2.2.6 on 2022-09-22 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pub_date',
        ),
    ]
